name: build-iso
on: 
  schedule:
    - cron: '0 9 * * *'
  push:
    branches: [ main ]
jobs:
  build-iso:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
    steps:
      - name: install necessary packages
        run: |
          mkdir /build-iso
          cd /build-iso
          pacman -Syu --noconfirm archiso grub git
          git clone https://github.com/lsproule/omakub-live.git omakub-live
          mkarchiso -v -o out omakub-live
          ls out
