name: build-iso
on: 
  schedule:
    - cron: '0 9 * * *'
  push:
    branches: [ main ]
jobs:
  build-iso:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
    steps:
      - name: build iso 
        run: |
          mkdir /build-iso
          cd /build-iso
          pacman -Syu --noconfirm archiso grub git
          git clone https://github.com/lsproule/omakub-live.git omakub-live
          mkarchiso -o out omakub-live
          ls out work
      - name: upload isos 
        uses: actions/upload-artifact@v4
        with:
          name: upload-isos 
          path: |
            /build-iso/out
