name: build-iso
on: 
  schedule:
    - cron: '0 9 * * *'
  push:
    branches: [ main ]
jobs:
  build-iso:
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
      - name: install necessary packages
        run: |
          mkdir /build-iso
          cd /build-iso
          pacman -Syu --noconfirm archiso
          cp -r /usr/share/archiso/configs/baseline archlive
          (
            cat <<EOF \
              base \
              cloud-init \
              hyperv \
              linux \
              mkinitcpio \
              mkinitcpio-archiso \
              open-vm-tools \
              openssh \
              pv \
              qemu-guest-agent \
              syslinux \
              virtualbox-guest-utils-nox \
              nmap \
              vim \
              base-devel \
              openssh \
              git \
              man-db \
              man-pages \
              lvm2 \
              mkinitcpio \
              mkinitcpio-archiso \
              mkinitcpio-nfs-utils \
              nvme-cli \
              nmap \
              zsh \
              wireless_tools \
              wpa_supplicant \
              tmux \
            EOF
          ) |  sed 's/ //g;s/\t//g' > archlive/packages.x86_64 
          cat archlive/packages.x86_64 
 
